### ISSUE TITLE
[Suggestion] Different particle

### ISSUE THREAD

**Issue by hotgeart** [ymc-thzi/clickspark.js#9]
Hi (sorry for my english),

That's sould be great if we can put more than one particle and not necessary an image.

Example : 

``` javascript
$('h1').clickSpark({     
    particle: ['<div class="particle-1"></div>', '<img src="/img-particle-2.png">', 'foo'],     
    // other stuff
});
```

With this you can make differents scale of an image. Or you can put div whatever you want.

So you can make an AMAZING PARTICLES RAINBOW§§§
![](http://stream1.gifsoup.com/view/793138/it-s-so-fluffy-o.gif)

**Comment by ymc-thzi** [comment]
Hi hotgeart,
thx for your proposal :+1: 
Particles are based on an canvas image obj. so I will only work with images or paths. The given particles are scalable by configuration, additionally they are scaled randomly in the code a bit. Also you can put the particle source wherever you want with

```
clickSpark.fireParticles($('.someDiv'));
```

If you want different colored particles, you can put them into one image file. But I will keep the idea to configure multiple images, thx for that :-)
